.TH comedi 7 ""
.SH NAME
\fBcomedi\fR - the Linux Control and Measurement Device Interface
.SH SYNOPSIS
\fB#include <comedi.h>\fR
.br
.SH DESCRIPTION
The \fBcomedi\fR package is a collection of hardware drivers and
library routines that can be used to communicate with a variety of
data acquisition boards, including A/D converters, D/A converters,
digital I/O and timers.

The hardware drivers that are installed on your system may include
one or more of the following:

	\fB8255\fR - Generic 8255 support
.br
	\fBdas08\fR - Keithley DAS08 and compatibles
.br
	\fBdt2811\fR - Data Translation DT2811
.br
	\fBdt2814\fR - Data Translation DT2814
.br
	\fBdt2817\fR - Data Translation DT2817
.br
	\fBdt282x\fR - Data Translation DT2821 series
.br
	\fBni_E\fR - National Instruments AT-MIO E series
.br
	\fBni_E\fR - National Instruments AT-MIO (Am9513 based)
.br
	\fBparport\fR - Standard PC parallel port digital I/O
.br
	\fBpcl711\fR - PC-LabCard PCL-711, 711B
.br
	\fBpcl711\fR - PC-LabCard PCL-725
.br
	\fBpcl711\fR - PC-LabCard PCL-726
.br
	\fBrti800\fR - Analog Devices RTI-800/815

.SH OTHER DOCUMENTATION

The following man pages may be useful:

\fBcomedi_config\fR(8), 

Additional text documentation is located in /usr/doc/comedi-0.5.0.

.SH VERSION

0.5.0

The current version can be found at ftp://stm.lbl.gov/pub/comedi.

.SH AUTHOR

David Schleef, <ds@stm.lbl.gov>

