#!/bin/bash
# This is the script that I use to make .tgz files for release
# It's not intended for general use, and if you want to
# understand how/why it works, read the code, don't ask me.

export LINUXDIR=/d/ds/linux/linux-2.2.17

export CVSROOT=opensource.lineo.com:/var/cvs

if [ ! "$1" ]
then
	echo -n "minor version: "
	read minor
else
	minor=$1
fi

let lastminor=$minor-1

tag=r0_7_$minor
version=0.7.$minor
lasttag=r0_7_$lastminor

echo 'removing export_tmp'
rm -rf export_tmp

mkdir export_tmp

cd export_tmp

echo "deleting tag $tag"
cvs rtag -d $tag comedi

echo "tagging $tag"
cvs rtag $tag comedi

echo "exporting"
cvs export -r $tag comedi

echo "generating patch"
cvs rdiff -u -r $lasttag -r $tag comedi >../patch-comedi-$version

mv comedi comedi-$version

mkdir comedi-$version/include/comedi
mkdir comedi-$version/include/modbuild
rm -rf comedi-$version/patches

sed -e "s/^SUBLEVEL.*/SUBLEVEL = $minor/" -e "s/^EXTRAVERSION.*/EXTRAVERSION = /" \
  comedi-$version/Makefile >Makefile.tmp
mv Makefile.tmp comedi-$version/Makefile

tar -czvf ../comedi-$version.tgz comedi-$version


