LINUXINCLUDE := $(COMEDI_PREPEND_CFLAGS) $(LINUXINCLUDE)

include comedi_kbuild.inc

obj-m += comedi.o
comedi-y := comedi_fops.o proc.o range.o drivers.o comedi_buf.o comedi_ksyms.o
comedi-$(COMEDI_CONFIG_RT) += rt_pend_tq.o rt.o
comedi-$(CONFIG_COMPAT) += comedi_compat32.o

obj-y += kcomedilib/
obj-y += drivers/

