#!/usr/bin/perl -w
# vi: set ts=4:

sub parse_devices;

@ARGV = ('-') unless @ARGV;

$ARGV=shift @ARGV;
if(!open(FILE,$ARGV)){
	warn "Can't open $ARGV: $!\n";
	exit 1;
}

while(<FILE>){
	push @lines,$_;
}

$driver = "";
while($_=shift @lines){
	if( m/^[\w-]+: / ){
		if($l){
			#print "$l\n";
			if($l =~ m/^Driver: /){
				$_ = $l;
				s/^Driver: //;
				$driver = $_;
			}
		}
		chomp;
		$l=$_;
	}elsif( m/^ / ){
		s/^ +//;
		chomp;
		$l="$l $_";
	}else{
		if($l){
			#print "$l\n";
			if($l =~ m/^Driver: /){
				$_ = $l;
				s/^Driver: //;
				$driver = $_;
			}
			if($l =~ m/^Devices: /){
				$_ = $l;
				s/^Devices: //;
				parse_devices($_);
			}
			$l="";
		}
	}
}


sub parse_devices
{
	my $devs = $_[0];
	my $mfr = "unknown";
	my $dev = "unknown";
	my $name = "unknown";

	#print("parse_devices $devs\n");

	while($devs){
		$_=$devs;
		if(m/^ *\[([^\]]+)\](.*)/){
			$mfr = $1;
			#print "recognized mfr $mfr\n";
			$devs = $2;
		}elsif(m/^ *\(([^\)]+)\)(.*)/){
			$name = $1;
			#print "recognized name $name\n";
			$devs = $2;
		}elsif(m/^ *([^\(,]+)(.*)/){
			$dev = $1;
			$devs = $2;
			$dev =~ s/ *$//;
			#print "recognized dev $dev\n";
		}elsif(m/^ *,(.*)/){
			$devs = $1;
			printf "%-28s %-17s %-17s %-10s\n", $mfr, $dev, $driver, $name;
		}else{
			print "parse error $_\n";
			$devs = "";
		}
	}
	printf "%-28s %-17s %-17s %-10s\n", $mfr, $dev, $driver, $name;
}


