#!/bin/bash

export CVSROOT=ds@cvs.comedi.org:/var/cvs
export CVS_RSH=ssh

topdir=$(pwd)

if [ ! "$1" ]
then
	echo -n "minor version: "
	read minor
else
	minor=$1
fi

lastminor=$(($minor - 1))

tag=r0_7_$minor
version=0.7.$minor
lasttag=r0_7_$lastminor

echo "deleting tag $tag"
cvs rtag -d $tag comedi

echo "tagging $tag"
cvs rtag $tag comedi

echo "exporting"
cvs export -r $tag -d comedi-$version comedi

echo "generating patch"
cvs rdiff -u -r $lasttag -r $tag comedi >patch-comedi-$version

cd comedi-$version

sed -e "s/^SUBLEVEL.*/SUBLEVEL = $minor/" -e \
	"s/^EXTRAVERSION.*/EXTRAVERSION = /" \
	Makefile >Makefile.tmp
mv Makefile.tmp Makefile
make drivers.txt

cd $topdir
tar -czf comedi-$version.tgz comedi-$version

